### ISSUE TITLE
change of `opens1.threadDisplayStyle` doesn't take effect until you refresh the tree view

### ISSUE THREAD

**Issue by Eskibear** [NessajCN/opens1#4]
Step to reproduce:
- open a thread. (by default it's markdown)
- open settings, change value of `opens1.threadDisplayStyle`, e.g. to "typescript"
- open another thread from the tree view.
- it's still open as markdown, and the filename is xxx.md
- click the refresh button on the tree view, then the settings take effect.

Suggest to add a listener to refresh the tree view via API `vscode.workspace.onDidChangeConfiguration`. 
This can also apply to other settings like `hiddenBoards`.

BTW this feature is super interesting! 👍

**Comment by NessajCN** [comment]
Great advice.

**Comment by NessajCN** [comment]
a753cc2
Done

**Comment by Eskibear** [comment]
https://github.com/NessajCN/opens1/commit/a753cc22ea97064efae26e4fc44f360f73208e61#diff-fa99aa5026842217d1270c4ccdf4b15d2e81015551e2d3836c528ac0145021a1R87-R89

It's suggested to only refresh when what you defined has changed... e.g.
```ts
vscode.workspace.onDidChangeConfiguration(e => {
        if (e.affectsConfiguration("opens1")) {
              // do the refresh 
        }
}
```
