### ISSUE TITLE
command 'opens1.refresh' not found

### ISSUE THREAD

**Issue by fulideplus** [NessajCN/opens1#6]
All commands not found.
![image](https://github.com/NessajCN/opens1/assets/41358423/6a7073bb-ed0f-47f4-aa5a-feaad49bb0d6)
It looks like casing by some vulnerabilities.After i using "npm audit fix",it was work.
![image](https://github.com/NessajCN/opens1/assets/41358423/8d654579-38bd-4887-8162-a0a7fde824a2)

**Comment by Eskibear** [comment]
> It looks like casing by some vulnerabilities

No, it's probably not.

From my logs, the command is not found because the extension failed activation. And the reason is VS Code removed keytar in v1.83. See https://code.visualstudio.com/updates/v1_83#_keytar-removed-from-vs-code @NessajCN you may want to switch to use `SecretStorage` api.

```
2023-10-26 10:46:04.908 [error] Activating extension nessaj.opens1 failed due to an error:
2023-10-26 10:46:04.908 [error] Error: \\?\c:\Users\yanzh\.vscode\extensions\nessaj.opens1-0.5.3\node_modules\keytar\build\Release\keytar.node is not a valid Win32 application.
\\?\c:\Users\yanzh\.vscode\extensions\nessaj.opens1-0.5.3\node_modules\keytar\build\Release\keytar.node
```

**Comment by Eskibear** [comment]
@NessajCN BTW if you insist using keytar, it's ok. Then you need to publish platform-specific extensions for each supported platform. From my perspective, it's cheaper to adopt SecretStorage API.

**Comment by NessajCN** [comment]
@Eskibear Thanks for feedback. I'll find a replace.

**Comment by Eskibear** [comment]
I unblock myself by adopting SecretStorage API, and I can send out a sample PR for your reference, which simply demonstrates how to use it. Looking forward to a new version with the fix! (which is important for me to moyu 😆  )

**Comment by NessajCN** [comment]
The new release f54e156 should work. Update the extension to 0.6.0
